# Basic Python

## 1. Split this string

In [3]:
s = "Hi there Sam!"

In [4]:
output = s.split()
print(output)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [6]:
print(f'The diameter of {planet} is {diameter} kilometers')

The diameter of Earth is 12742 kilometers

## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [39]:
a = d.get('k1')[3]
b = a.get('tricky')[3]
c = b.get('target')[3]
print(c)

'hello'

# Numpy

In [41]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [42]:
result_1 = np.zeros(10)
print(result_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [45]:
result_2 = np.ones(10)*5
print(result_2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

## 5. Create an array of all the even integers from 20 to 35

In [51]:
adc = np.arange(21,32)
print(adc)

[21 22 23 24 25 26 27 28 29 30 31]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [57]:
arr = np.arange(0,9)
output = arr.reshape(3,3)
print(output)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [61]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [71]:
import pandas as pd

data = {'Fruits': ['Apple','Mango','Orange'],
        'Price_1kg': [100, 150, 120],
        'Colour': ['Red','Yellow','Orange']}
output = pd.DataFrame(data)

   Fruits  Price_1kg  Colour
0   Apple        100     Red
1   Mango        150  Yellow
2  Orange        120  Orange

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [81]:
import pandas as pd

output = pd.date_range("01-01-2023", "02-10-2023")

print(output)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [84]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

output = pd.DataFrame(lists)
print(output)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24